### ISSUE TITLE
QOrmEntityListModel::data from QVector<T*>

### ISSUE THREAD

**Issue by raphaelcotty** [dpurgin/qtorm#15]
If the propertyValue.type() is QVector<T*> then the value is cast into QVector<QObject*>.
Creating a QVariant from a QObject* creates a QVariant with a bool type.
So the QVariantList only has a list of boolean.
I tried to find a way to create a QVariant<T*> without success.

**Comment by dpurgin** [comment]
Hey Raphael,

thanks, I'll look into it. Perhaps, there is a way to use [custom QVariant converters](https://doc.qt.io/qt-5/qmetatype.html#registerConverter) to provide such a conversion but I'm not sure yet.

**Comment by dpurgin** [comment]
Ah, I got it, and that was easier than I thought. The code that converted `QVector<T*>` to `QVariantList` relied on a non-explicit constructor of QVariant, but since there is no `QVariant(QObject*)`, `QVariant(bool)` was selected. I've been working closer with QVariant since I had written that code in QtOrm, so there is a simple fix for it in the linked pull request. 

I've changed the `navigationdb` so that the provinces list uses this feature and lists the names of the communities instead of their total count: 

![image](https://user-images.githubusercontent.com/8401313/107116909-c6763f80-6876-11eb-8d31-bb7b4bd9f91e.png)

Can you please check if this works in your case too?

**Comment by raphaelcotty** [comment]
Working for me too.
Thanks!
