### ISSUE TITLE
Mark properties as transient

### ISSUE THREAD

**Issue by dpurgin** [dpurgin/qtorm#18]
Some properties should be excluded from persistence, e.g. by using STORED

**Comment by dpurgin** [comment]
@raphaelcotty 
Hi Raph, I've implemented some mapping metadata customization using `Q_ORM_CLASS` and `Q_ORM_PROPERTY` in the pull request attached. Among others, there is an option to mark a property transient (see the description [here](https://github.com/dpurgin/qtorm/tree/18-transient-properties#mapping-customization).

Could you please check if it works for you?

**Comment by raphaelcotty** [comment]
Thanks. Going to test it.

**Comment by raphaelcotty** [comment]
I see an issue when loading a database in qormsqliteprovider.cpp line 298.
It doesn't happen with the navigationdb because the data is already in the cache.
So in my example the QOrmSqliteProviderPrivate::read creates a new instance (calling makeEntityInstance) which calls QOrmPrivate::setPropertyValue for each property, including the TRANSIENT which doesn't have a read method...
I guess QOrmSqliteProviderPrivate::fillEntityInstance needs somehow to pass all the TRANSIENT properties.

**Comment by dpurgin** [comment]
Thanks, I've pushed a fix, should work now!
